#! /usr/bin/env bash

# Este script toma un backup de la base de datos, lo comprueba y lo copia en la
# maquina remota

# Se supone que la configuracion de ambas maquinas es la misma (nombre de instance
# directorios, usuarios, nombre de base de datos, etc.)

# Directorio de backups. En ambas maquinas debe ser el mismo.
BACKUP_DIRECTORY=/home/db2inst1/backups

# Nombre o IP de la maquina remota.
REMOTE_SERVER=23.21.64.225

# Nombre de la base de datos
DATABASE=WFSCPD

# Cantidad de archivos de backups full a conservar (contienen .0. en el nombre)
BACKUP_QTY=3

# Nombre de la instancia.
INSTANCE=db2inst1

# Carga el ambiente de DB2
if [ -f /home/db2inst1/sqllib/db2profile ]; then
    . /home/db2inst1/sqllib/db2profile
fi
#set -xv
cd $BACKUP_DIRECTORY

echo "Haciendo el backup db $DATABASE"
BACKUP=`db2 backup db $DATABASE online compress WITHOUT PROMPTING`
RET=$?

if [[ $RET -eq 0 ]] ; then
  BACKUP=`echo $BACKUP | awk '{print $11}'`
  FILENAME=$(ls -1 $BACKUP_DIRECTORY/*$BACKUP*)

  echo "Chequando archivo de backup - $FILENAME"
  CHECK=`db2ckbkp $FILENAME`
  RET=`echo $CHECK | awk '/successful/ {print "Successful"}'`
  
  if [[ $RET == "Successful" ]] ; then

    echo "Copiando backup a maquina de contingencia - $REMOTE_SERVER"
    scp $FILENAME $REMOTE_SERVER:$BACKUP_DIRECTORY

    echo "Contando backups locales"
    QTY=$(ls -1 $BACKUP_DIRECTORY/$DATABASE.0.$INSTANCE* | wc -l)
    echo "Backup locales $QTY"
    if [[ $QTY -gt $BACKUP_QTY ]] ; then
      while [[ $QTY -gt $BACKUP_QTY ]] ; do
        OLD_BACKUP=`ls -1t $DATABASE.0.$INSTANCE* | tail -1`
        echo "Moviendo el backup mas viejo a /mnt - $OLD_BACKUP"
        mv $OLD_BACKUP /mnt/db2
        QTY=$(ls -1 $BACKUP_DIRECTORY/$DATABASE.0.$INSTANCE* | wc -l)
      done
    fi

    echo "Contando backups remotos"
    REMOTE_QTY=$(ssh $REMOTE_SERVER ls -1t $BACKUP_DIRECTORY/$DATABASE.0.$INSTANCE\* | wc -l)
    echo "Backups remotos $REMOTE_QTY"
    if [[ $REMOTE_QTY -gt $BACKUP_QTY ]] ; then
      while [[ $REMOTE_QTY -gt $BACKUP_QTY ]] ; do
        OLD_REMOTE=$(ssh $REMOTE_SERVER ls -1t $BACKUP_DIRECTORY/\*$DATABASE\* | tail -1)
        echo "Borrando backup remote mas viejo - $OLD_REMOTE"
        ssh 23.21.64.225 rm $OLD_REMOTE
        REMOTE_QTY=$(ssh $REMOTE_SERVER ls -1t $BACKUP_DIRECTORY/$DATABASE.0.$INSTANCE\* | wc -l)
      done
    fi
  else
    echo "Borrando backup corrupto"
    rm $FILENAME
    exit 2
  fi
else
  echo "El backup fallo! Es necesario volver a lanzarlo."
  echo $BACKUP
  exit 1
fi
