#! /usr/bin/env bash

# Llama al sistema de rotacion de logs y mueve logs pasados al directorio old.

# Carga el ambiente de DB2
if [ -f /home/db2inst1/sqllib/db2profile ]; then
    . /home/db2inst1/sqllib/db2profile
fi
#set -xv

db2diag -A -readfile

DIAGPATH=`db2 get dbm cfg | awk '/\(DIAGPATH\)/ {print $7}'`

cd $DIAGPATH

mv db2diag.log_* old
