#! /usr/bin/env bash

# Llama al sistema de rotacion de logs y mueve logs pasados al directorio old.

# Archivo para logs (output)
LOGS=/home/db2inst1/scripts/db2/output/rotateLogsOutput.log

# Carga el ambiente de DB2
if [ -f /home/db2inst1/sqllib/db2profile ]; then
    . /home/db2inst1/sqllib/db2profile
fi
#set -xv

if [[ ! -e $LOGS ]] ; then
  touch $LOGS
  chmod 666 $LOGS
fi
if [[ ! -w $LOGS ]] ; then
  echo "Archivo de logs (output) no es escribible: $LOGS"
  exit
fi

echo "----------" >> $LOGS
date >> $LOGS

db2diag -A -readfile >> $LOGS

DIAGPATH=`db2 get dbm cfg | awk '/\(DIAGPATH\)/ {print $7}'`

cd $DIAGPATH

mv -v db2diag.*.log_* old >> $LOGS
